# 1. Kısım: DEPLOYMENT (Uygulamayı Yöneten Kısım)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  labels:
    app: ml-inference
spec:
  replicas: 3  # MLOps : 3 tane kopya istiyoruz (Scalability)
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
    spec:
      containers:
      - name: ml-container
        image: ml-model:v1 # Minikube içindeki local image'ı kullanacak
        imagePullPolicy: Never # Docker Hub'dan çekmeye çalışma, local'e bak
        ports:
        - containerPort: 8000
        
        # MLOps : Kaynak Limitleme (GPU simülasyonu gibi düşün)
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
            
        # MLOps : Self-Healing (Otomatik İyileştirme)
        # K8s her 5 saniyede bir /health adresine bakar. Cevap alamazsa Pod'u öldürüp yenisini açar.
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---

# 2. Kısım: SERVICE (Dış Dünyaya Kapı Açan Kısım)
apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  selector:
    app: ml-inference # Bu etiketle eşleşen Pod'lara trafiği yönlendir
  type: LoadBalancer # Dışarıdan erişilebilir IP ver
  ports:
    - protocol: TCP
      port: 80      # Dışarıdan gelen istek portu (Browser için)
      targetPort: 8000 # İçerideki uygulamanın portu
